### ISSUE TITLE
Incompatibility between EDR-DOS Kernel and SvarCOM

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/bugz#38] opened 2023-11-16 22:45 UTC
When SvarCOM is launched as first process under EDR-DOS kernel via SHELL= config.sys entry, the system freezes when SvarCOM tries to launch an external process. If SvarCOM is launched as a child shell by another command processor (4DOS or EDR-DOS command.com), everything works. I will try to further investigate this issue. But this is new terrain to me. So I am not confident that I can achieve any results in this. I especially have no idea yet, how to debug this problem, since I can not launch a debugger from the shell prompt to debug the shell :/

First thing I will try at weekend is to see if this happens also under the MS-DOS kernel when running SverCOM as first shell, and if other shells fail under the EDR-DOS kernel.

**Comment by mateuszviste** [comment] 2023-11-16 23:10
I will have to take the time to reproduce this issue, as it is not a very easy (nor friendly) territory.
What I can say now is that your description of the problem makes me think the problem is located in one of these two places:
- either in RMOD.ASM (which is the part that actually executes the external program)
- or in the way SvarCOM sets its PSP so RMOD is called after the transient part of SvarCOM stops

The design here is that SvarCOM sets up in memory a little piece of code called RMOD (for Resident MODule). This tiny thing is the designated (by the transient portion of SvarCOM) as SvarCOM's parent. When SvarCOM needs to execute an external program it does two things:
1. patches up the fields in RMOD's memory with information what program should be loaded next
2. exits

When SvarCOM exits, the kernel is supposed to check who its parent is by examining the PSP of the ended process, and hand control to this parent. Since RMOD's address is the designated as a parent, the CPU should jump to RMOD's address. RMOD then sees that it has pre-filled fields with the name of some external program and asks the kernel to load it.

I designed this solution to minimize as much as possible the amount of conventional memory used by SvarCOM when another program runs. RMOD takes only 2K.

Anyway: either RMOD fails to load the external program, or the kernel fails to hand control to RMOD after SvarCOM quits. Maybe EDR-DOS does not like me "hot-patching" my own PSP with the address of something that I have put myself in memory.

**Comment by boeckmann** [comment] 2023-11-17 15:33
I tested SvarCOM under the MS-DOS 6.22 kernel today. This seems to run well (at least nothing crashes). Having it running under the EDR-DOS kernel is not such imortant to me. So do not invest much time unless you are interested yourself.

**Comment by mateuszviste** [comment] 2023-11-17 16:13
Thanks for checking this up. This does not necessarily mean there is a bug in the EDR-DOS kernel since the way SvarCOM operates is somewhat uncommon, but it does seem like some form of incompatibility with MS-DOS, or at least a different behavior. I wonder if @ecm-pushbx would be inclined to comment on this?

**Comment by ecm-pushbx** [comment] 2023-11-17 16:40
> Thanks for checking this up. This does not necessarily mean there is a bug in the EDR-DOS kernel since the way SvarCOM operates is somewhat uncommon, but it does seem like some form of incompatibility with MS-DOS, or at least a different behavior. I wonder if @ecm-pushbx would be inclined to comment on this?

I may get around to testing this later. lDebug can be installed in three ways that may help debug this problem:

1. As a bootable debugger then loading the kernel using a `boot protocol edrdos` command. My recent EDR-DOS builds include a debugger check which is an `int3` followed by a conditional branch. Toggling the Carry Flag at this point will make the kernel not initialise interrupt 0, 1, and 3 vectors to help debugging the system past this point.
2. As a device driver using a `DEVICE=` line in DCONFIG.SYS. Just run the debuggee like with a `g` command to return the control flow to the DOS that loaded us.
3. As a resident debugger using an `INSTALL=` line in DCONFIG.SYS. Run the `tsr` command to install the debugger residently. Then trace or run to continue the DOS load process.

> The design here is that SvarCOM sets up in memory a little piece of code called RMOD (for Resident MODule). This tiny thing is then designated (by the transient portion of SvarCOM) as SvarCOM's parent.

From a cursory glance at your description: This sounds like it should work. Do you also make sure to set the `dword [PSP:2Eh]` of the new parent process to refer to a valid stack?

**Comment by ecm-pushbx** [comment] 2023-11-17 16:44
Links to relevant files in the repo:

http://svn.svardos.org/filedetails.php?repname=SvarDOS&path=%2Fsvarcom%2Ftrunk%2Frmodinit.c

http://svn.svardos.org/filedetails.php?repname=SvarDOS&path=%2Fsvarcom%2Ftrunk%2Frmod.asm

**Comment by ecm-pushbx** [comment] 2023-11-17 16:57
I reviewed the two files and I think there are two more possible error sources:

1. You seem to never modify the parent process field (`word [PSP:16h`) ?
2. You do not fix the Process Handle Table of rmod to refer to its own table in its own PSP.

**Comment by mateuszviste** [comment] 2023-11-17 17:09
> Do you also make sure to set the `dword [PSP:2Eh]` of the new parent process to refer to a valid stack?

Thank you very much for your diligent lookup!

You may very well have hit the nail on the head here. PSP:2E is an opaque structure that I know nothing about. I naively copy the PSP of the transient SvarCOM to prefix RMOD's code and reassign only its owner and env segment. I wonder what generic approach could be used to be sure RMOD ends up with a valid PSP.

I would prefer to avoid hand-crafting the content of the PSP, because I suppose these "opaque" fields might have different meaning across different versions of DOS. I quickly looked into RBIL, but did not find any function that would say "please create a valid PSP for me".

I have two possible solutions in mind:
1. put RMOD'd code at the top of SvarCOM and make the first instance of SvarCOM go TSR (hence leaving behind only the RMOD part).
2. separate RMOD into a separate COM program, which would be loaded in SHELL=, and then RMOD would call the actual SvarCOM shell

I am more inclined towards the 1st solution as it keeps everything in a single file, so it is simpler for users.

Is there another way that I might have missed?

**Comment by mateuszviste** [comment] 2023-11-17 23:08
Thanks for the nice (and very impressive!) example code.

I hacked SvarCOM so it presets RMOD's PSP with a valid stack, empty JFT and set a self-pointing parent:
http://svn.svardos.org/diff.php?repname=SvarDOS&path=%2Fsvarcom%2Ftrunk%2Frmodinit.c&rev=1587&peg=1587

Unfortunately it does not fix the issue. My VM still freezes when trying to execute an external command.
This weekend I will try out least to figure out at what moment exactly the freeze happens. Maybe that will tell us something more.

**Comment by ecm-pushbx** [comment] 2023-11-18 08:36
> `myptr[0x32] = 0`

This should be 20. And I don't think you want an all-closed PHT, as this will inherit to the transient SvarCOM process once it reloads, and any process that you spawn for an external command likewise.

> `myptr[0x2e] = 254; /* I abuse the PSP's command line tail as stack */`

This is wrong and will potentially overwrite part of your buffers that start past the PSP. This is because the `dword [PSP:2Eh]` is not used merely to set SS:SP but rather to find the stack frame created by the int 21h call. Therefore the int 21h call that terminates the child process will then pop a number of registers off starting from the address stored in the PSP. I think you should run a DOS call (eg 21.4B7F or 21.48) with the stack that you desire and then retrieve the offset `word [PSP:2Eh]` from the current PSP to stick it into your parent. (The segment is trivial to obtain.)

**Comment by mateuszviste** [comment] 2023-11-18 12:29
> > `myptr[0x32] = 0`
> 
> This should be 20. And I don't think you want an all-closed PHT, as this will inherit to the transient SvarCOM process once it reloads, and any process that you spawn for an external command likewise.

Yes, that's not very good, but it was only a test. I did try setting it to 20 first (and reset the entire JFT to 0xff which I understand means "empty file descriptor slot") but that did not change the issue.
Nonetheless you are right, it should be 20 and I did set it back to 20 earlier today.

> > `myptr[0x2e] = 254; /* I abuse the PSP's command line tail as stack */`
> 
> This is wrong and will potentially overwrite part of your buffers that start past the PSP. This is because the `dword [PSP:2Eh]` is not used merely to set SS:SP but rather to find the stack frame created by the int 21h call. Therefore the int 21h call that terminates the child process will then pop a number of registers off starting from the address stored in the PSP.
> I think you should run a DOS call (eg 21.4B7F or 21.48) with the stack that you desire and then retrieve the offset `word [PSP:2Eh]` from the current PSP to stick it into your parent. (The segment is trivial to obtain.)

Hmm, you are correct that I thought indeed this was only supposed to hold the parent's stack. Thank you for the clarification, I'm sometimes a tad slow to catch up. :)

I fail to understand how allocating a memory block would help me, though. BTW what is the 21.4B7F call? RBIL does not list it.

I've moved the SP pointer back by 64 bytes so DOS can POP/PUSH stuff without damaging RMOD, but still no luck.
http://svn.svardos.org/comp.php?repname=SvarDOS&compare[]=%2Fsvarcom%2Ftrunk%2Frmodinit.c@1588&compare[]=%2Fsvarcom%2Ftrunk%2Frmodinit.c@1589

Interestingly, the issue depends on the type of program that is about to be launched. Here is a test floppy:
[edr.zip](https://github.com/SvarDOS/bugz/files/13400251/edr.zip)

When mounted under VirtualBox It boots all right. Then, if I try to run SVED.COM the editor loads fine, and the VM freezes only when I try to quit Sved.
If, however, I try to run MEM.EXE instead, then the freeze happens immediately.

I hope to find some time this evening to fiddle some more with this and understand at what time exactly things go wrong.

**Comment by ecm-pushbx** [comment] 2023-11-18 13:10
> t. I did try setting it to 20 first (and reset the entire JFT to 0xff which I understand means "empty file descriptor slot") but that did not change the issue.

A PHT entry of 0FFh indeed means a closed file handle. This sounds to me like you did in fact close all handles of your RMOD process. So anything using the standard file handles (stdin, stdout, stderr + stdaux and stdprn) will appear to freeze as it never gets any input, and also cannot display output. This would explain why Sved works (it does I/O to the ROM-BIOS int 10h/int 16h/screen buffer) until you try returning to SvarCOM but mem fails immediately (uses DOS I/O to std handles).

**Comment by ecm-pushbx** [comment] 2023-11-18 13:17
Another problem: you "patch up RMOD's PSP: Parent's PSP segment @ 0x16-0x17" but do you set the parent of your own PSP to be equal to the RMOD process anywhere? If so I did not spot it.

**Comment by ecm-pushbx** [comment] 2023-11-18 13:36
> I fail to understand how allocating a memory block would help me, though. BTW what is the 21.4B7F call? RBIL does not list it.

21.48 is a "normal" DOS call that likely builds the expected stack frame to match the frame that process termination expects. (It expects a stack frame that matches the one created by 21.4B00.) 21.33 for example may be not a "normal" call as some DOS calls may build different stack frames.

I chose 21.48 simply because it is a call my TSR init needs to do anyway before relocating its process.

As noted in the comments of my TSR example, dosemu2 may interfere with the 21.48 call's stack frame. This is why I added an optional call to 21.4B7F (ds:dx -> empty string) which I hope to be an invalid call. DOS call interceptions like dosemu2's must handle at least 21.4B00 in a way that builds the expected stack frame so that when DOS plugs in the Parent Return Address it will return to the parent process with its original stack before the `int 21h`. The invalid subfunction will, I hope, be handled together with all 21.4B subfunctions to build the expected stack frame.

(I did just add an update to my TSRs in which they store bp on the stack rather than relying on DOS to preserve it successfully. But the ss:sp needs to be preserved correctly.)

**Comment by mateuszviste** [comment] 2023-11-18 14:01
Hello ECM, you are spot on. I said "freeze" earlier, but it is not the case. It's simply - as you said - that stdout is no longer visible. If I quit Sved and type "sved" again, I do get back to the editor. So everything "serious" under the hood seem to work all right. And it was the case since the beginning (I tested with an unmodified version of SvarCOM and the behaviour is the same - ie. it all works, but system becomes blind). I could have thought of that myself, shame on me.

I commented out my JFT-being-set-to-FFh code, but that's not enough. I suspect I am doing something wrong also in rmod.asm regarding file descriptors. I will analyze it with more care in the evening. Thanks for all your valuable help!

**Comment by ecm-pushbx** [comment] 2023-11-18 14:10
> It's simply - as you said - that stdout is no longer visible. If I quit Sved and type "sved" again, I do get back to the editor. So everything "serious" under the hood seem to work all right.

This is odd, as I would expect that SvarCOM's stdin is also closed and when it uses 21.0A then it shouldn't be able to read input either. If I do get around to debugging this then this is an open question.

**Comment by mateuszviste** [comment] 2023-11-18 14:41
It's more odd than that even. I did not want to annoy you about this in my earlier message, but since you started... :)
When I quit SVED and the system "freezes" (becomes blind), I am able to type in a new "sved" command and not only SvarCOM does receive the command all right, but it also displays it (ie. I see what I type). In other words, it would seem like the INT 21h,AH=0Ah call used for buffered input is not subject to the same stdout limitations as the AH=40h service used to print out data on screen.
It is also curious that this all works fine on both FreeDOS and MS-DOS.

**Comment by mateuszviste** [comment] 2023-11-21 21:36
Okay, it works now.

> Another problem: you "patch up RMOD's PSP: Parent's PSP segment @ 0x16-0x17" but do you set the parent of your own PSP to be equal to the RMOD process anywhere? If so I did not spot it.

Being out of ideas I added the code that sets "my own" (ie. transient SvarCOM) parent to be RMOD's segment, and this solved the issue:
http://svn.svardos.org/diff.php?repname=SvarDOS&path=%2Fsvarcom%2Ftrunk%2Frmodinit.c&rev=1595&peg=1595

Thank you again, ECM.

I should have listened earlier instead of spending a couple of evenings on debugging approaches that failed (I was mostly focusing on stdout duplications and redirections as that seemed to be the most obvious candidate for EDR-DOS becoming blind).

Still, I do not understand why this solved the problem. How come that an invalid parent segment in the PSP leads to file descriptors being lost? And why is stdout lost, but typing commands still show up on screen? That's a mystery to me, and will probably have to stay that way.

Important thing is that now SvarCOM is compatible with FreeDOS, MS-DOS and EDR-DOS, and that's cool.
I like the EDR-DOS kernel so far, as it is more compact than FreeDOS. I wonder about making it the default SvarDOS kernel, but will have to test it a lot more first to make sure that nothing else breaks.

**Comment by ecm-pushbx** [comment] 2023-11-22 08:48
> Still, I do not understand why this solved the problem. How come that an invalid parent segment in the PSP leads to file descriptors being lost?

I don't think there is an "invalid" parent, rather some sort of initial process. For FreeDOS this initial process is at segment 60h. This process runs 21.4B00 to start the SHELL= application. If it terminates then the initial process gains control again.

By the way, when you terminate SvarCOM for good you should restore both the parent process field as well as the Parent Return Address (int 22h) in your transient PSP to refer back to the original parent. Are you doing that yet?

> And why is stdout lost, but typing commands still show up on screen?

It is possible that the int 21h service 0Ah doesn't use the file handles.

**Comment by mateuszviste** [comment] 2023-11-22 10:16
> For FreeDOS this initial process is at segment 60h. This process runs 21.4B00 to start the SHELL= application. If it terminates then the initial process gains control again.

That's where my confusion started. Until now I thought the "parent PSP" field is just an informational thing for PSP walkers and such, and that the "giving control back" part depends only on the address inside the int 22h field. That worked okay on FreeDOS/MSDOS (maybe by chance), but I see now that things are more complicated than that. Lesson learnt, I will make sure to set up the "parent PSP segment" field whenever I touch int 22h.

> By the way, when you terminate SvarCOM for good you should restore both the parent process field as well as the Parent Return Address (int 22h) in your transient PSP to refer back to the original parent. Are you doing that yet?

Not yet, no. When it is sayonara time, I try to guess if I am the root process, and if I conclude that I am not, then I only change the int 22h field of my transient part:

http://svn.svardos.org/filedetails.php?repname=SvarDOS&path=%2Fsvarcom%2Ftrunk%2Fsayonara.c

I will make the change so the parent PSP segment is also reverted to its original value.

BTW, last year Robert reported this ugly issue <https://github.com/SvarDOS/bugz/issues/41> with Volkov Commander. I am quite lost as to how to handle this, esp. since VC's is closed-source. I was half-hoping that fixing the issue with EDR-DOS could also fix VC, but it is not the case. You seem extremely fluent in this subject - would you have any hints where/what/how I should approach this?

**Comment by boeckmann** [comment] 2023-11-22 15:25
> Okay, it works now.

Great to hear that!

> Important thing is that now SvarCOM is compatible with FreeDOS, MS-DOS and EDR-DOS, and that's cool. I like the EDR-DOS kernel so far, as it is more compact than FreeDOS. I wonder about making it the default SvarDOS kernel, but will have to test it a lot more first to make sure that nothing else breaks.

I think distribution as package would be the safer option for the start, until it is thorougly tested. It would be nice if all available kernels get their own directory under X:\KERNEL. Like X:\KERNEL\FD2042 X:\KERNEL\DR231116 ... 

It would also be nice to have a boot loader capable of selecting between the different kernels at startup. I doubt that this will fit into sector 1. But perhaps we can load an intermediate loader from the boot partition, which then loads the actual kernal. Shall we make a separate issue for that topic?

**Comment by ecm-pushbx** [comment] 2023-11-22 16:08
> It would also be nice to have a boot loader capable of selecting between the different kernels at startup. I doubt that this will fit into sector 1. But perhaps we can load an intermediate loader from the boot partition, which then loads the actual kernal. Shall we make a separate issue for that topic?

Ad time! You can use [lDebug as a bootable debugger](https://pushbx.org/ecm/web/#projects-ldebug) for this. Install a boot sector loader to a DOS FAT FS drive using the included `instsect.com` program, setting the filename using an `/F=` switch if you do not want to use the default. Place the debugger executable in the root directory. Upon boot, you should be greeted by the debugger prompt `-` or `~-`. Enter eg `boot protocol freedos` or `boot protocol edrdos` to load a kernel, then on success run a `q` command to run the kernel.

The first boot file usually can be loaded from a subdirectory as well, the second file may not work that way (eg for EDR-DOS) as it may need to be in the root directory.

Alternatively, you may want to use MetaKern by Eric Auer (and [extended by me](https://hg.pushbx.org/ecm/metakern)) which works differently: You have to set up the boot sector loaders as separate files with the BPB initialised for your file system. Then you append the boot sectors to the MetaKern kernel, and load that from a FreeDOS-kernel-compatible loader. It will pop up a menu with timeout at boot time.

**Comment by mateuszviste** [comment] 2023-11-22 16:14
> I think distribution as package would be the safer option for the start, until it is thorougly tested. It would be nice if all available kernels get their own directory under X:\KERNEL. Like X:\KERNEL\FD2042 X:\DR231116 ...

Yes of course, I have no intention of enforcing any hard coded choice. The idea is that the *default* SvarDOS kernel could be EDR-DOS (once I tested it enough to be confident it is not significantly worse than DOS-C), but the user would be free to install & use the FreeDOS kernel via pkgnet pull & pkg install.

The only catch here is that the kernel needs to have its SYS companion + suitable bootloader so the users would have to be instructed about how to activate the given kernel.

I like the EDR kernel because it is full assembly and it has a lower memory footprint. But sadly it has also a higher on-disk footprint, which mitigates the coolness factor a bit:

FD KERNEL = 89 sectors (45329 bytes, kernel.sys)
EDR KERNEL = 143 sectors (35495 + 36973 bytes, drbio.sys and drdos.sys)

So as far as floppy installs are concerned, FD kernel is better because it helps limiting the amount of floppies, but then on "production" EDR is probably more desirable as it seems to be more RAM efficient (assuming no regressions). Of course for consistency the same kernel must be used for both floppies and installation, so it is a hard choice. :)

> It would be nice if all available kernels get their own directory under X:\KERNEL. Like X:\KERNEL\FD2042 X:\KERNEL\DR231116 

Definitely, yes. Such directory would contain the kernel, some sort of documentation and probably the dedicated SYS tool.

> It would also be nice to have a boot loader capable of selecting between the different kernels at startup.

That would be very nice, yes. Probably not as CORE (because I want CORE to be as simple as possible + fit on a single floppy), but having some alternative bootloaders on the repo would be good.

**Comment by ecm-pushbx** [comment] 2023-11-22 16:36
> > For FreeDOS this initial process is at segment 60h. This process runs 21.4B00 to start the SHELL= application. If it terminates then the initial process gains control again.
> 
> That's where my confusion started. Until now I thought the "parent PSP" field is just an informational thing for PSP walkers and such, and that the "giving control back" part depends only on the address inside the int 22h field. That worked okay on FreeDOS/MSDOS (maybe by chance), but I see now that things are more complicated than that. Lesson learnt, I will make sure to set up the "parent PSP segment" field whenever I touch int 22h.

Yes, precisely. The process termination works with several parts:

* Current PSP (either from the SDA field or for some old-style calls from the user CS)
* Parent PSP, to be set as the new SDA current PSP
* The int 22h (actually used as Parent Return Address), int 23h, and int 24h fields from the terminating PSP
* The Process Handle Table from the terminating PSP, to close all handles
* The MCB chain to free all DOS MCBs owned by the terminating PSP
* The current DOS stack recorded in `dword [PSP:2Eh]` in the parent PSP

Process handles and MCBs are **not** freed if the termination is from a TSR interrupt (27 or 21.31). (NB that means if you do not want to retain any handles when running 21.31, you have to close them manually before that call. Otherwise the Process Handles and even the System File Table entries may be leaked.) The same is true if the parent PSP is equal to the terminating PSP.

> > By the way, when you terminate SvarCOM for good you should restore both the parent process field as well as the Parent Return Address (int 22h) in your transient PSP to refer back to the original parent. Are you doing that yet?
> 
> Not yet, no. When it is sayonara time, I try to guess if I am the root process, and if I conclude that I am not, then I only change the int 22h field of my transient part:
> 
> http://svn.svardos.org/filedetails.php?repname=SvarDOS&path=%2Fsvarcom%2Ftrunk%2Fsayonara.c
> 
> I will make the change so the parent PSP segment is also reverted to its original value.

Yes, you should do that.

> BTW, last year Robert reported this ugly issue #41 with Volkov Commander. I am quite lost as to how to handle this, esp. since VC's is closed-source. I was half-hoping that fixing the issue with EDR-DOS could also fix VC, but it is not the case. You seem extremely fluent in this subject - would you have any hints where/what/how I should approach this?

I may get around to debugging this later. My approach would be to run FreeCOM+VC+EDIT under the debugger (lDebug resident in `tsr` mode, or installed before FreeCOM), intercept some int 21h calls (`bp new ptr ri21p when value ah in 4B, 4C, 4D` plus `install indos`), and put breakpoints on where 21.4B calls should return (examine using `u ptr [ss:sp]` when an int 21h breakpoint has returned control to the debugger). Then you can examine the machine state using `dm` or `rvp` or `d ptr [psp:34] l word [psp:32]`. Next retry with SvarCOM instead and figure out what differs, other than the segment addresses.

**Comment by boeckmann** [comment] 2023-11-22 16:51
> FD KERNEL = 89 sectors (45329 bytes, kernel.sys) EDR KERNEL = 143 sectors (35495 + 36973 bytes, drbio.sys and drdos.sys)

My EDR KERNEL test build is not UPX compressed. But @ecm-pushbx hints in the build instructions indicate that compression is possible. I will try to make a new package with a comressed kernel. I anyway have to prepare a new package (fixed a minor inconvinience regarding FAT-32 formatting).

I have a rather busy work week. Will take some time...

**Comment by boeckmann** [comment] 2023-11-22 16:58
> > It would also be nice to have a boot loader capable of selecting between the different kernels at startup. I doubt that this will fit into sector 1. But perhaps we can load an intermediate loader from the boot partition, which then loads the actual kernal. Shall we make a separate issue for that topic?
> 
> Ad time! You can use [lDebug as a bootable debugger](https://pushbx.org/ecm/web/#projects-ldebug) for this. Install a boot sector loader to a DOS FAT FS drive using the included `instsect.com` program, setting the filename using an `/F=` switch if you do not want to use the default. Place the debugger executable in the root directory. Upon boot, you should be greeted by the debugger prompt `-` or `~-`. Enter eg `boot protocol freedos` or `boot protocol edrdos` to load a kernel, then on success run a `q` command to run the kernel.
> 
> The first boot file usually can be loaded from a subdirectory as well, the second file may not work that way (eg for EDR-DOS) as it may need to be in the root directory.
> 
> Alternatively, you may want to use MetaKern by Eric Auer (and [extended by me](https://hg.pushbx.org/ecm/metakern)) which works differently: You have to set up the boot sector loaders as separate files with the BPB initialised for your file system. Then you append the boot sectors to the MetaKern kernel, and load that from a FreeDOS-kernel-compatible loader. It will pop up a menu with timeout at boot time.

@ecm-pushbx I will have a look at that! Have to spend some time to get known to all the features your debugger offers. I uploaded the lDebug 6 package to the SvarDOS repository. However, I had to change the .lsm file from your .svp package. The version string was not accepted by PKG. I had to remove the "release" from "release 6".

**Comment by boeckmann** [comment] 2023-11-22 17:02
> The only catch here is that the kernel needs to have its SYS companion + suitable bootloader so the users would have to be instructed about how to activate the given kernel.

For the start we can provide a SYS.COM with each kernel, like I did it with the EDR kernel packages. That would be the most straightforword for the user: Change to the kernel dir and do a SYS X: /UPDATE. Ready...

**Comment by ecm-pushbx** [comment] 2023-11-22 17:11
> > FD KERNEL = 89 sectors (45329 bytes, kernel.sys) EDR KERNEL = 143 sectors (35495 + 36973 bytes, drbio.sys and drdos.sys)
> 
> My EDR KERNEL test build is not UPX compressed. But @ecm-pushbx hints in the build instructions indicate that compression is possible. I will try to make a new package with a comressed kernel. I anyway have to prepare a new package (fixed a minor inconvinience regarding FAT-32 formatting).
> 
> I have a rather busy work week. Will take some time...

Yes, I described that in https://hg.pushbx.org/ecm/edrdos/file/e1dbcad5136e/doc/build.but#l134 (It seems I do not have this build manual uploaded anywhere yet.) This is the original EDR-DOS compression support as delivered by Udo Kuhnt, who presumably used DR-DOS Debug but as noted it works with lDebug as well. On the forum another method to compress I think the drbio file was posted, the other file is the same as the original.

> I will have a look at that! Have to spend some time to get known to all the features your debugger offers. I uploaded the lDebug 6 package to the SvarDOS repository. However, I had to change the .lsm file from your .svp package. The version string was not accepted by PKG. I had to remove the "release" from "release 6".

Hmm, can this be changed? Where exactly does it check that?

**Comment by boeckmann** [comment] 2023-11-22 17:18
There is a package checker script on the web interface running over the packages that complained. The results are displayed there: http://svardos.org/?p=repo&showlogs=1#logs. lDebug is obviously is not shown anymore, because I changed it.

Perhaps @mateuszviste can say what is the exact reason. My initial guess is the version update code algorithm of PKGNET?

**Comment by ecm-pushbx** [comment] 2023-11-22 17:27
I looked at pkg and pkgnet a bit but didn't see it. Is the blank what's causing the problem? If possible I'd rather drop the blank only rather than the entire word.

**Comment by mateuszviste** [comment] 2023-11-22 17:33
> I may get around to debugging this later. My approach would be to run FreeCOM+VC+EDIT under the debugger (lDebug resident in `tsr` mode, or installed before FreeCOM), intercept some int 21h calls (`bp new ptr ri21p when value ah in 4B, 4C, 4D` plus `install indos`), and put breakpoints on where 21.4B calls should return (examine using `u ptr [ss:sp]` when an int 21h breakpoint has returned control to the debugger). Then you can examine the machine state using `dm` or `rvp` or `d ptr [psp:34] l word [psp:32]`. Next retry with SvarCOM instead and figure out what differs, other than the segment addresses.

Thanks for the hints, I will try to figure out how to use it later this week. lDebug is a very impressive piece of software, it's just that I never used a DOS debugger yet, my only experience is limited to gdb on Linux, but that's a different world. :)

> Perhaps @mateuszviste can say what is the exact reason. My initial guess is the version update code algorithm of PKGNET?

The issue is that with "weird" versions pkgnet won't be able to figure out which version is newer and which version is older, so "pkgnet checkup" might end up either ignoring some available updates or even proposing to upgrade packages to older versions.

To compare versions, the pkgnet backend translates version strings into an array of values. It knows how to decipher a bunch of exotic version strings already, but "release X" is none of them. The exact code is here, function vertoarr():

http://svn.svardos.org/filedetails.php?repname=SvarDOS&path=%2Fbuildidx%2Fbuildidx.php

> If possible I'd rather drop the blank only rather than the entire word.

I can look into supporting a new versioning scheme if that's important for you. What other word could there be in place of "release" ? Could you provide me with a few examples of versions so I can understand the logic?

**Comment by ecm-pushbx** [comment] 2023-11-22 17:47
> > I may get around to debugging this later. My approach would be to run FreeCOM+VC+EDIT under the debugger (lDebug resident in `tsr` mode, or installed before FreeCOM), intercept some int 21h calls (`bp new ptr ri21p when value ah in 4B, 4C, 4D` plus `install indos`), and put breakpoints on where 21.4B calls should return (examine using `u ptr [ss:sp]` when an int 21h breakpoint has returned control to the debugger). Then you can examine the machine state using `dm` or `rvp` or `d ptr [psp:34] l word [psp:32]`. Next retry with SvarCOM instead and figure out what differs, other than the segment addresses.
> 
> Thanks for the hints, I will try to figure out how to use it later this week. lDebug is a very impressive piece of software, it's just that I never used a DOS debugger yet, my only experience is limited to gdb on Linux, but that's a different world. :)

Yes, gdb is a little different. I'd say lDebug is more strictly line-oriented, and it deals with arbitrary text or debugger command line variables less well than gdb. (The new Extensions for lDebug which will be included in release 7 (available now in current release builds) somewhat bridge the gap to parsing arbitrary text from their command line tails. And set.eld/variable.eld allow to modify and read DOS-style environment variables.)

> > Perhaps @mateuszviste can say what is the exact reason. My initial guess is the version update code algorithm of PKGNET?
> 
> The issue is that with "weird" versions pkgnet won't be able to figure out which version is newer and which version is older, so "pkgnet checkup" might end up either ignoring some available updates or even proposing to upgrade packages to older versions.

Isn't there a date stamp field that could be used for this?

> To compare versions, the pkgnet backend translates version strings into an array of values. It knows how to decipher a bunch of exotic version strings already, but "release X" is none of them. The exact code is here, function vertoarr():
> 
> http://svn.svardos.org/filedetails.php?repname=SvarDOS&path=%2Fbuildidx%2Fbuildidx.php
> 
> > If possible I'd rather drop the blank only rather than the entire word.
> 
> I can look into supporting a new versioning scheme if that's important for you. What other word could there be in place of "release" ? Could you provide me with a few examples of versions so I can understand the logic?

Examples so far are only "release X" where X is a digit from "0" to "6". Probably you could just strip the word "release " and then handle the rest as you were. Going forward there will probably be a "release 10" at some point. I do not intend to add any other keywords at this time. (The symbolic build option may be enabled at some point but it will probably be packed with a different package name rather than adding to the version field.)

**Comment by mateuszviste** [comment] 2023-11-22 18:59
> Isn't there a date stamp field that could be used for this?

No, there is no such field. The FreeDOS LSM files contain a "entered-date" (or similar) field, but it's the date when the package has been created, not the date of the software release, so totally useless.

Besides, even if there would be a proper software-released-date field, it still wouldn't be good because version 2.0 could have been released in august, while in september the author still decided to add a minor fix to an older 1.5.1 version.

Also, such field would require more human work. I largely prefer to deal with information that is already there. Works good so far. :)

> Probably you could just strip the word "release " and then handle the rest as you were.

I will do that, no issue. And then I will rename the ldebug package so it's "release 6" again, as it was initially.
This may lead to some occasional glitchy display like "update available: ldebug version Release 7", but that's functionally harmless so I'm fine with it. And most of all I do want to respect your nomenclature wish.

> For the start we can provide a SYS.COM with each kernel, like I did it with the EDR kernel packages. That would be the most straightforward for the user: Change to the kernel dir and do a SYS X: /UPDATE. Ready...

I agree. I also have to finally implement <https://github.com/SvarDOS/bugz/issues/28>. I was dragging my feet on this one as it's very boring stuff, but now there's a tangible need so it has to be done.

**Comment by mateuszviste** [comment] 2023-11-24 14:00
Hi, just to say that I have added a tolerance for "build xxx" versions and I renamed the ldebug version string to its original "release 6" form.

![image](https://github.com/SvarDOS/bugz/assets/9503501/113ae4f0-0e0b-4e6f-ba76-7d6364f06539)

I am closing this issue now, since the EDR-DOS incompatibility bug has been identified and fixed. Thank you Bernd for reporting it, and Thank You ECM for your perceptive analysis, insightful hints and patience.

**Closed by mateuszviste** 2023-11-24 14:00 UTC
Labels: SvarCOM
