### ISSUE TITLE
DIR /S fails with insufficient memory, fails to enumerate all dirs

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/bugz#147] opened 2024-12-30 12:52 UTC
SvarCOM `DIR /S` fails with an `insufficient memory` error when run on C: multiple times. After that it fails to reload itself. This was originally reported at the [classing computing forum](https://forum.classic-computing.de/forum/index.php?thread/34643-svardos-dr-dos-is-reborn-as-an-open-source-operating-system/&postID=516634#post516634).

I also noticed that it fails to enumerate all directories. A recursive directory list of the SVARDOS installation dir shows the files listed in the [FILES.TXT](https://github.com/user-attachments/files/18274736/FILES.TXT), missing multiple directories. This ran through without throwing a memory error.

<img width="454" alt="Bildschirmfoto 2024-12-30 um 13 43 15" src="https://github.com/user-attachments/assets/535f298b-9b83-4cc5-ab72-d19d59d3d4a1" />

**Comment by boeckmann** [comment] 2024-12-30 13:41
At least the recursion problem also occurs when SvarCOM is started under DosBox-X. I will try to figure out what is going on...

**Comment by mateuszviste** [comment] 2024-12-30 14:38
Something's wrong indeed. When running DIR/S on the root C: drive within DOSEMU several times I managed to make it crash horribly.

![image](https://github.com/user-attachments/assets/e6fef00e-0900-4aa1-b72e-2c2581ec422b)

Interestingly, MEM does not report any increase of memory between every DIR/S attempt, so it does not seem to be a "simple" case of memory leak.

**Comment by mateuszviste** [comment] 2024-12-30 14:44
also, in my test with DOSEMU I was able to produce the crash only when combining /S with /O (either via DIRCMD or passed as an explicit argument). Running DIR/S over 30 times on my root C: drive without /O did not lead to any visible issues. But doing it with /O led to a MCB PANIC after only 3 attempts. So maybe the problem is not in recursion, but in ordering, and /S only exacerbates the problem as it makes the ordering routine work more heavily.

**Comment by boeckmann** [comment] 2024-12-30 14:47
When doing a DIR/S under the SvarCOM trunk dir (DosBox-X) it does not walk into the `svarlang.lib` and `toys` dirs.

I tried to build a debug version of SvarCOM. This command.com containing debug info is a 108K .COM file. I do not know if this size per se is a problem, but this crashes right from the start when launched under DosBox. Too sad. Would be really helpful to have a binary able to run under the WD debugger to do some symbolic debugging. I will do further diagnostics on why this debug version does not run...

**Comment by mateuszviste** [comment] 2024-12-30 15:01
it's a COM file, so I do not think it can be greater than 64K (tiny model).

About the /S/O crashes: they occur with version 2024.8 but not with 2024.7. The major change was removing libc dependencies, in this process I had also to remove qsort() and implement my own DTA-sorting routine. Maybe this invention of mine is broken.

Also, be careful with /S on emulated drives - the hypervisor needs to keep track of "open" FindFirst calls because the "first sector of directory" does not make sense on modern filesystems. The hypervisor (emulator) might drop some such mappings if there are too many, leading to missing entries. I had observed this with TREE, but might also relate to DIR/S.

**Comment by boeckmann** [comment] 2024-12-30 15:33
The debugging info is simply appended to the .COM file (according to a hex diff). If I strip the debugging info from the .COM file with the WSTRIP utility, the size of the .COM is reduced to below 64k. And this version runs under DosBox.

However, the 108K .COM containing the full debug info seems to run fine under the EDR kernel, and also when I load and run it with DEBUG under DosBox-X. So in general the size seems not to be a problem, but the DosBox-X .COM loader is not able to handle this. Maybe @ecm-pushbx has some insights on this .COM size topic?

**Comment by boeckmann** [comment] 2024-12-30 15:58
MS-DOS refuses to load with "Program too big to fit in memory". I will make another issue about the debugging stuff to not pollute this issue any further.

**Comment by ecm-pushbx** [comment] 2024-12-30 16:26
Yes, I was about to reply already when I noticed the mention of the too big file. Flat-format executables are commonly supported only up to some (inexact) limit below 64 KiB. The 256 bytes of PSP also have to fit at the beginning of the CS, and leaving some space for the stack at the end of the segment is good as well. So about 63.5 KiB is a more realistic limit than a full 64 KiB.

Flat-format files are usually called with a ".COM" filename extension, vs segmented MZ executables with ".EXE", but the filename is just a convention. A file named .COM can actually contain an MZ header and this way it can run even when larger than 64 KiB.

You can instead load a flat-format file larger than 64 KiB with a special loader. lDebug (and probably original MS-DOS or MSDebug too) allows this, but the stack will point within the loaded data then. lDebug [has a special switch, /E,](https://pushbx.org/ecm/doc/ldebug.htm#invoking-app) which causes it to allocate the stack in a separate segment to help using it with ".BIG" files.

The debugger's own build process creates the executable image as a ".BIG" file. It then wraps that image in either an inicomp stage, directly as the MZ image of the lDOS iniload stage, or [within an "MZ shim" stage](https://hg.pushbx.org/ecm/ldebug/file/e2fafd3b7668/source/mzshim.asm). Example use is [in the mak script](https://hg.pushbx.org/ecm/ldebug/file/e2fafd3b7668/source/mak.sh#l466). Importantly it uses the auto stack feature which, alike the /E switch to lDebug, sets up the stack in an SS != PSP and SS != CS. The default is to use a CS == PSP, which involves an MZ header field for init CS of -16. With an init IP of 256 this can be used to load big images in a way that is similar to running a smaller flat-format / .COM file, except for the SS != PSP and there not being a zero word as a return address on the initial stack.

**Comment by boeckmann** [comment] 2024-12-30 19:49
@mateuszviste I have to admit that while looking at cmd_dir it is the first time for me having problems understanding your code :)

**Comment by boeckmann** [comment] 2024-12-30 22:12
There is something going on with the DTA stack. When I do a `dir/s` on the SvarCOM trunk dir, `dtastacklen` is 1 when inside the `CMD` directory.

<img width="678" alt="Bildschirmfoto 2024-12-30 um 22 45 37" src="https://github.com/user-attachments/assets/ac99a2cf-b5c2-4c5f-bfa8-2b4313a37e94" />

Under toys however, `dtastacklen` is 0.
<img width="690" alt="Bildschirmfoto 2024-12-30 um 22 39 49" src="https://github.com/user-attachments/assets/e51cf1e2-27ae-4633-91d8-03906f803b2f" />

And the listing stops after processing the `TOYS` dir.

**Comment by boeckmann** [comment] 2024-12-31 01:33
I think I have found the error causing not all directories to be shown with `DIR/S`. The problem was that when a search for subdirectories was continued and another dir was found, the DTA stack size was not increased before handling the sub-directory. See https://github.com/SvarDOS/core/commit/1501983a2c0d3852ba8728865de5bfdf3316424f

**Comment by boeckmann** [comment] 2024-12-31 01:46
Seems that as a side effect the insufficient memory error is gone, too. At least I can `dir/w/s` my hole C: multiple times without running into memory errors.

**Comment by mateuszviste** [comment] 2024-12-31 06:44
Looks like you nailed it! Fantastic job, thank you. I am surprised that the thing worked more or less at all. I will do some tests with dosemu and then I think it will be time for a new release.

**Comment by mateuszviste** [comment] 2024-12-31 15:46
I tested in DOSEMU. Now DIR/S/O does not crash (good!), but instead I get the error that was described initially in this issue:

![image](https://github.com/user-attachments/assets/8b3fb0ac-ec80-4737-b0dd-f5ce3c7f3d8e)

This happens after a single DIR/S on my root C:.

**Comment by mateuszviste** [comment] 2024-12-31 16:26
> This happens after a single DIR/S on my root C:.

Erratum: it happens after a single DIR/S/O. The /S alone works fine, it's again the combination of /S and /O that leads to the issue.

**Comment by mateuszviste** [comment] 2024-12-31 16:45
dtabuf was allocated at every /S recursion (and not freed in between). should be fixed now. https://github.com/SvarDOS/core/commit/52270b11ce76a31a19346c7ac694f3dbef412552

dtabuf buffering is used only when /O is involved, which explains why the issue was only occurring with /S/O and not with /S alone.

**Closed as completed by mateuszviste** 2024-12-31 16:45 UTC
Labels: bug, SvarCOM

**Comment by boeckmann** [comment] 2024-12-31 16:55
I just was in the process to write that there seems to be an asymmetry between cmd_dir_farfree and cmd_dir_farmalloc (which is inside the iter loop). Great you fixed it already!
