### ISSUE TITLE
Make network setup more user friendly

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/bugz#60] opened 2024-01-22 18:51 UTC
I noticed myself that the hardest part of getting SvarDOS running was the setup of the packet drivers to make use of pkg / pkgnet. There are no drivers included on the installation media, so the user has to download them himself via the package repository. But before that he has to find out which package he actually needs.

All in all this makes it very hard for Average Joe to benefit from PKGNET. So I am wondering if the user could be assisted in this process, without generating too much work.

**Comment by bttrx** [comment] 2024-01-22 19:01
closed as a duplicate of #20

**Closed as completed by bttrx** 2024-01-22 19:01 UTC
Labels: duplicate, enhancement
