### ISSUE TITLE
pkgnet hangs on my 8088

### ISSUE THREAD

**Issue by evan** [SvarDOS/bugz#34] opened 2023-08-21 06:06 UTC
I have a Leading Edge Model D, connected to the internet with an Intel 8/16 NIC.

Any time I run "pkgnet" it hangs. I can't ctrl-C, but I can ctrl-alt-delete. I have tried the EXP16 packet driver as well as the EXP8 driver from oldskool.org. Even running it without any packet driver loaded, it hangs immediately. 

I don't know how to debug this further.

**Comment by mateuszviste** [comment] 2023-08-21 08:59
I will prepare a debug version of pkgnet so we can understand better at what point it hangs exactly. Give me a day or two.

Just to be sure: does your packet driver works with any other network tools?

**Comment by evan** [comment] 2023-08-21 12:02
Yes, it works fine with MTCP and EtherDFS (both from SvarDOS).

I’m currently using the SvarDOS pkg system with MS-DOS 6.22, but it also hung when I was using the default FreeDOS install.

**Comment by mateuszviste** [comment] 2023-08-21 19:27
Here is a debug version of pkgnet. It displays a list of steps before printing the result, for example:

![image](https://github.com/SvarDOS/bugz/assets/9503501/4ec850c0-7f4a-4579-96b2-bf153a605134)

Could you please run it on your machine and tell at what steps it stops? Try to run it without any argument first to see if it is at least able to print out its help screen.

How much available memory do you have btw? To be honest I'm not sure if pkgnet can run on a 256K PC, I will have to test this.
[pkgnet.zip](https://github.com/SvarDOS/bugz/files/12401694/pkgnet.zip)

**Comment by evan** [comment] 2023-08-21 20:04
No help text, nothing. I have 543k free. 

If it matters, I believe my Intel 8/16 is on IO 360h but I would have to double check. The XT-IDE is on 340h and the RTC is on 300h.

![IMG_6842](https://github.com/SvarDOS/bugz/assets/210/c5472a25-17a2-4421-af99-709556c500e1)

**Comment by mateuszviste** [comment] 2023-08-21 21:03
Have you waited a little bit? On my 8086 pkgnet takes up some 20s to load, maybe for you it's longer for some reason?

**Comment by evan** [comment] 2023-08-21 21:30
Yes, I have waited.

After a big loop of `LODSB` it seems to lock the machine at this instruction (MS-DOS debug output):

![IMG_6845](https://github.com/SvarDOS/bugz/assets/210/e9d3599e-bf93-4d93-a1d4-c8fda2c57f0c)

**Comment by mateuszviste** [comment] 2023-08-21 22:36
Thank your for the details. At this point I think this become more of an issue about "running an OpenWatcom application", since the pkgnet code is not even reached yet. The pkg tool is compiled in compact model, while pkgnet is large. I wonder if there's anything in watcom's large model startup code that could confuse your machine. Let me think about this for some time.

In the meantime, any chance you could confirm that the pkgnet.exe file you are testing is not corrupted? Just to be safe... (BSUM = B786)

**Comment by evan** [comment] 2023-08-22 02:15
Confirmed the checksum. 

My machine doesn't have an 8087. I saw some references online to problems with OpenWatson FPU detection routines on the 8088 specifically; maybe something to look into.

**Comment by mateuszviste** [comment] 2023-08-22 22:30
You may be right that the 8087 detection thing might be the problem. Unfortunately I have no way to reproduce the issue so I am totally blind on this issue. All I can say is that yes, pkgnet does pull in 8087-checking code, while pkg does not.

Someone named Scali did a very nice research on the topic back in 2015. I have applied (I think) the necessary patch and here is a binary for you to test... It's worth a shot, but really - I work in the dark here.

[pkgnet_8088_patch.zip](https://github.com/SvarDOS/bugz/files/12413435/pkgnet_8088_patch.zip)

**Comment by evan** [comment] 2023-08-22 22:57
It works!

These were the references I found: 
  - https://www.os2museum.com/wp/learn-something-old-every-day-part-vii-8087-intricacies/
  - https://www.vogons.org/viewtopic.php?t=42518

What version of OpenWatson do you use? Are you building on Linux? 

The only issue I encountered is that if I run the (new) binary from an etherDFS share, it hangs on exit and doesn't return to the shell. Running it from the C drive works fine.

**Comment by mateuszviste** [comment] 2023-08-23 00:07
I'm glad it works for you, thanks for testing. I'm using OpenWatcom v1.9, building everything on SvarDOS.
I have released a new formal pkgnet version right now. How to update:

```
pkgnet pull pkgnet
pkg update pkgnet.svp
```

Hanging at exit when being launched from an EtherDFS share is not really expected. Can you confirm it still happens with the current repository version (ie. once you upgraded it), and if yes - create a separate bug report? As for now I'm closing this issue, as the 8088 hang is solved. Thanks again for your kind reports!

**Closed by mateuszviste** 2023-08-23 00:07 UTC
Labels: pkgnet

**Comment by evan** [comment] 2023-08-23 00:34
I used pkgnet to update pkgnet. The release build doesn't hang when the binary is on the share anymore.

Thanks for all the fixes. Was pkgnet the only OpenWatcom/FPU binary in SvarDOS? I assume any similar programs would have the same problem.

**Comment by mateuszviste** [comment] 2023-08-23 00:54
You are certainly right that other applications being built with OW 1.9 *and* floating point likely exhibit the same issue.
But are there any other? Honestly I don't know. If so, then it's up to their respective authors/maintainers to fix them anyway. The only other software of mine I can think about in this context is Gopherus - and it's already on my todo list waiting for a rebuild with the 8088-FPE-compatible libc hacked by Scali.

There is some hope about OW19 BTW: I just noticed that the message on openwatcom.org changed a couple of months ago, apparently a reboot is on its way. That would be really nice.

**Comment by evan** [comment] 2023-08-23 01:04
Is OpenWatcom 2.0 not good?
